apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-app
  labels:
    app: identity-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-app
  template:
    metadata:
      labels:
        app: identity-service-app
    spec:
      containers:
        - name: identity-service-app
          image: microdocker0215/identity-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7001

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service-svc
spec:
  ports:
    - targetPort: 7001
      port: 80
  selector:
    app: identity-service-app